name: xml_converter
description: The XML Converter is a Dart package that provides functionality to convert XML strings to JSON format and Dart classes and saves it in the specified project structure.,This package is designed to facilitate the handling of XML data in Dart applications by offering a simple and efficient way to transform XML into usable formats.
version: 1.2.0
repository: https://github.com/ahmedtalal/xml_converter

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
 xml2json: ^6.2.5
 xml: ^6.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^4.0.0
  test: ^1.24.0
