name: xml_converter
description: The XML Converter is a Dart package that provides functionality to convert XML strings to JSON format and Dart classes,This package is designed to facilitate the handling of XML data in Dart applications by offering a simple and efficient way to transform XML into usable formats.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
 xml: ^6.5.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
